# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170808_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_verified',
            new_name='has_voted',
        ),
    ]
