# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('party', models.CharField(max_length=30)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
