# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='post',
            field=models.CharField(choices=[('PRE', 'President'), ('VPR', 'Vice-President'), ('SEC', 'Secretary'), ('MEM', 'Member'), ('TRE', 'Treasurer')], max_length=3),
        ),
    ]
