# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170604_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('UML', 'CPN-UML'), ('MAOIST', 'CPN - MAOIST'), ('CONGRESS', 'NEPALI CONGRESS'), ('INDEPENDENT', 'INDEPENDENT'), ('MPRF', "Madhesi Pepole's Right Forum")], max_length=30),
        ),
    ]
