# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170619_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='static/candidates/im.jpg', upload_to='static/candidates/'),
        ),
    ]
