# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(default='static/candidates/im.jpg', upload_to='static/candidates/'),
        ),
    ]
