# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170806_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
